### ISSUE TITLE
WAC app can't start after deploying the GatewayPluginSample DLL

### ISSUE THREAD

**Issue by LiangJy123** [microsoft/windows-admin-center-sdk#165]
Hi ,
I  try the Gateway Plugin sample, build and put the DLL to target directory.

![image](https://user-images.githubusercontent.com/13048899/113104764-7cd12200-9233-11eb-81a3-3d7dee228f53.png)

Then as the document said , I restart the Windows Admin Center process.

But it can't be started.

Log at EVENT VIEW:
![image](https://user-images.githubusercontent.com/13048899/113105695-742d1b80-9234-11eb-89fa-e52112069924.png)

Can you offer some suggestions on how to troubleshoot this problem?

**Comment by mattatmsft** [comment]
Hi - 

Did you install Windows Admin Center in Dev Mode?  Check the purple note here: https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/extend/prepare-development-environment#install-prerequisites

Let me know if that got set up, and we can roll forward from there.

**Comment by LiangJy123** [comment]
Hi Matt,
It works , thank you very much.

![image](https://user-images.githubusercontent.com/13048899/113267021-7791d700-9308-11eb-96ac-db0007c89628.png)

**Comment by hezhiyu1980** [comment]
@mattatmsft Hi Mattatmsft, if we want use https to access WAC and connect to WAC Gateway Plugin, we should not install WAC in dev mode. Event log tell me I need to sign my dll. Do you how to sign the dll? Thanks!!

**Comment by LiangJy123** [comment]
> @mattatmsft Hi Mattatmsft, if we want use https to access WAC and connect to WAC Gateway Plugin, we should not install WAC in dev mode. Event log tell me I need to sign my dll. Do you how to sign the dll? Thanks!!

Hi @hezhiyu1980  , I find a way to sign ,but not sure it works . you can have a try.
Doc：
https://docs.microsoft.com/en-us/dotnet/framework/tools/signtool-exe 
![image](https://user-images.githubusercontent.com/13048899/143418527-4349afc2-13ce-4aa3-979c-d351a7082ff8.png)

Sample:
https://docs.microsoft.com/en-us/windows/win32/seccrypto/using-signtool-to-sign-a-file
![image](https://user-images.githubusercontent.com/13048899/143418427-9d220b60-c2ab-48a3-ba7c-3af339b7c62f.png)
