### ISSUE TITLE
Documentation on how to use the sme- controls and styles

### ISSUE THREAD

**Issue by B4DschK4Pp** [Microsoft/windows-admin-center-sdk#217]
Hi there,

is there any documentation available on how to use, for example the sme-pivot style to get a tabbed experience?

I  must be doing something wrong, as I always get the error "Pivot must contain child tabs. Expected at least one (1) tab".

Regards

**Comment by donatwork** [comment]
Did you look at the developer tools extension and SDK GitHub repo. Something like this.
```
<sme-pivot>
<sme-pivot-tab role="tab" tabindex="0">
 <span/>
</sme-pivot-tab>
</sme-pivot>
```

**Comment by B4DschK4Pp** [comment]
Thank you.  I tried that with no luck. 
Also checked out the SDK documentation, but wasn't able to find the developer tools, as the link in the documentation is dead. [Developer Tools](https://github.com/microsoft/windows-admin-center-sdk/blob/master/windows-admin-center-developer-tools)

**Comment by donatwork** [comment]
There are lots of examples in the GitHub for pivots. For example dev-guide/modules/controls/pivot/pivot-example.component.html

**Comment by B4DschK4Pp** [comment]
Thanks a lot. I've only been browsing MASTER... Sorry for bothering.

**Comment by donatwork** [comment]
No worries. Hope we can share info we we both seem to be learning as we go. I wish that there could be a better forum for WAC developers. The Microsoft Tech Community content seems more geared towards end users. Wish someone at Microsoft could create a forum more focused on developing extensions.

Sometimes when I need to look for something I just need to go to the CLI, for example, from the top of the source tree in Git bash:

`find dev-guide -type f -name '*.html' -exec grep -l '</sme-pivot-tab>' {} \;`
