### ISSUE TITLE
Question: Manage Connections

### ISSUE THREAD

**Issue by claudiospizzi** [Microsoft/windows-admin-center-sdk#22]
Hi all

Quick Question: Is it possible to develop an extension to manage connections. My idea is creating a custom extension for our company to load all servers as connections from a central database, in our case the CMDB, So none of our admins need to add them manually.

**Comment by mattatmsft** [comment]
You can use the new shared connections in Service Mode to do this, but it does not connect to your DB.  You will have to script a CSV output from the DB for input into the Shared Connection list.
