### ISSUE TITLE
Build Gateway plugin under .net5 can work

### ISSUE THREAD

**Issue by hezhiyu1980** [Microsoft/windows-admin-center-sdk#222]
Hi @mattatmsft,
We want to call Yarp(microsoft reverse proxy) library to implement our Gateway Plugin. Yarp is developed under .NET5.0, so I try to build this sample under .NET5.0. After deployed this dll to WAC, error appeared when I connect to the gateway, error message is "{"error":{"code":"FileNotFoundException","message":"Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified."}}"
I'm a new guy in windows .net development, my question is there a way to implement Gateway Plugin under .net5?

**Comment by donatwork** [comment]
I've asked for this before. Currently you can only use .Net 4.6.2. Even if you get past the .Net 5 problem you will run into an issue where the plugin method ProcessRequest will not be found. See https://github.com/microsoft/windows-admin-center-sdk/issues/166.

**Comment by hezhiyu1980** [comment]
@donatwork 
Thanks for your answer, don't know when the WAC will port to .net5 or .net6 ==!
