### ISSUE TITLE
developer tools example won't build with gulp

### ISSUE THREAD

**Issue by abbottbd** [Microsoft/windows-admin-center-sdk#23]
I'm brand new to typescript so this may be a stupid issue :-).

I've followed the MS docs for setting up my environment, then I've downloaded and unziped this repo.  When I go to the "windows-admin-center-developer-tools" directory and issue the 'gulp build' command I'm getting an error:

ERROR in D:/MyStuff/Downloads/windows-admin-center-sdk-master/windows-admin-center-sdk-master/windows-admin-center-developer-tools/src/main.ts
Module build failed: Error: D:\MyStuff\Downloads\windows-admin-center-sdk-master\windows-admin-center-sdk-master\windows-admin-center-developer-tools\src\main.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (D:\MyStuff\Downloads\windows-admin-center-sdk-master\windows-admin-center-sdk-master\windows-admin-center-developer-tools\node_modules\@ngtools\webpack\src\
angular_compiler_plugin.js:662:23)
    at plugin.done.then (D:\MyStuff\Downloads\windows-admin-center-sdk-master\windows-admin-center-sdk-master\windows-admin-center-developer-tools\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
 @ multi ./src/main.ts

I'm not sure how to fix this as in the tsconfig it seems that the pattern src\**\*.ts should include 'src\main.ts'.

**Comment by mattatmsft** [comment]
Not a stupid issue, that code was way old, so we removed it.  The new DevTools are in-product, so you shouldn't have this problem anymore.
