### ISSUE TITLE
Connection client using port 80 -- I don't know where I should post my question

### ISSUE THREAD

**Issue by tlsalex** [microsoft/windows-admin-center-sdk#54]
Hello, what I understand is windows admin center using PowerShelI to connect to target ,that is manage target via Powershell , However,in my case, the default port 5985 is block by security software on my windows 10 client.  But it's reachable via port 80 , I try to find an option to use port 80 when I connect to windows 10 client within windows admin center , but seems no way to do that.

 

Any advise ?

 

BR

**Comment by mattatmsft** [comment]
Hi there - 
Windows Admin Center makes extensive use of PowerShell remoting and WinRM.  Port 5985 is one of the WinRM default ports, and must be open for Windows Admin Center to work.  Double check that WinRM is enabled, and you should be good to go.  At this time there is no way to configure WAC to use WinRM on a different port.

**Comment by tlsalex** [comment]
Hey , you are right, but winrm can listen on 5985 and 80 at the same time, by enable EnableCompatibilityHttpListener .
I mean we don't need to change 5985 to 80 , instead just enable EnableCompatibilityHttpListener , than poewershell can reach remote target with 80 , but WAC can not instruct powershell to use  another port ,only the default behavior.
WAC should make an improvement on this matter.
![80](https://user-images.githubusercontent.com/36788337/60378187-51634700-9a51-11e9-96c6-8bc312545578.png)

**Comment by tlsalex** [comment]
Please help to reopen this issue
