### ISSUE TITLE
Open source the angular component inside the sdk 

### ISSUE THREAD

**Issue by badre429** [microsoft/windows-admin-center-sdk#61]
this sdk has a set of usefull angular component 
It'll be great if you can open source thous components and make it as separte project

**Comment by Harrioson** [comment]
Microsoft window is an operating system, 
which is needed to be loaded in a computer after purchasing it.
https://www.techsovibe.com/microsoft-windows/

**Comment by engstrumpan** [comment]
This ^ and/or make sure to upgrade the library to a supported version of Angular, version 10 at a minimum
