### ISSUE TITLE
not able to load my extension 

### ISSUE THREAD

**Issue by ar-india** [microsoft/windows-admin-center-sdk#71]
hi,
I tried to load my dev tool extension created after following the steps mentioned in https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/extend/develop-tool

but when i run gulp serve -p 4201 nothing happens.

installed wac in dev mode. "msiexec /i WindowsAdminCenter1910.msi DEV_MODE=1"
2 .i ran the gulp command from cmd line
3. i went to wac browser and on console dialog (after pressing f12 in browser) i gave "MsftSme.sideLoad("http://localhost:4201")"
4 then i refresh my browser but my new extension is never loaded.
Please help

**Comment by ar-india** [comment]
ok i figured out that the msdn does not provide the correct gulp command

it should be "gulp serve --port 4201" and not "gulp serve --p 4201"

after this i am now getting the below error

Mixed Content: The page at 'https://<localhost>/servermanager/connections/server/<localhost>/tools/nimbletool' was loaded over HTTPS, but requested an insecure resource 'http://localhost:4201/modules/nimble.nimbletool/?version=s-1.643.0'. This request has been blocked; the content must be served over HTTPS.

how to fix this

**Comment by mattatmsft** [comment]
It sounds like you installed WAC in prod mode instead of Dev.  Prod serves over HTTPS and when you do the gulp serve for your extension, it only serves over HTTP.  Check out the note [HERE](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/extend/prepare-development-environment#install-prerequisites)

You will have to uninstall WAC in order to re-install in Dev mode.

**Comment by illfated** [comment]
(Ref. https://github.com/MicrosoftDocs/windowsserverdocs/issues/921 for the comment in the closed issue ticket.)

**Comment by ar-india** [comment]
> It sounds like you installed WAC in prod mode instead of Dev. Prod serves over HTTPS and when you do the gulp serve for your extension, it only serves over HTTP. Check out the note [HERE](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/extend/prepare-development-environment#install-prerequisites)
> 
> You will have to uninstall WAC in order to re-install in Dev mode.

Thanks for the response.

No i have installed the WAC in DEV_MODE through command line. 
I am using windows server 2016 as my OS. and this is a workgroup machine.

I have one more question. The odc says to provide port num as 6516 for standlalone . Can i provide the same port number in workgroup machine here? the reason i am asking this is that when i give this port number , i am not able to even open the WAC in browser.
but when i provide the port number as 443 atleast i can open WAC in browser.

**Comment by ar-india** [comment]
here is the screenshot of the installer. Please note that the url provided (https://:6516) 
![wac install error](https://user-images.githubusercontent.com/57393285/70449751-8b3c7d00-1ac8-11ea-8269-51703720893b.png)

wac web page not opening after installation 

![wac_error2](https://user-images.githubusercontent.com/57393285/70450454-becbd700-1ac9-11ea-8b95-2d8339606515.png)

**Comment by alexanderboswell** [comment]
This is a known issue but DEV_MODE=1 is not supported if you are installing on a server SKU.  If you need to sideload an extension, you'll need to install Windows Admin Center on a Windows 10 Client in DEV_MODE.

**Comment by illfated** [comment]
Thank you for pointing out that limitation. I was thinking maybe it could have anything to do with a limitation that the installer would not handle the install correctly when run from a network drive.

**Comment by ar-india** [comment]
thanks alexander.

**Comment by chris-lionetti** [comment]
I have spent hours trying to figure out that DEV_MODE=1 doesn't work on the server SKU, this should be documented on the Github site that walks you through the installlation of DEV_MODE as one of the pre-requisites

**Comment by RameshJaiswar** [comment]
I run my WAC SDK in local https://localhost:4201 

while loading inside the window admin centre feeds showing error Message
 Couldn't read extension feed(s) for , https://localhost:4201/.

So I checked in inspect (F12) inside showing only unavailable feeds

<img width="498" height="64" alt="Image" src="https://github.com/user-attachments/assets/c9f7443b-a111-472b-b7a0-d9398fab42a2" />


so please help me
